version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-change-root}
      - MARIADB_DATABASE=${DB_NAME:-codrandom}
      - MARIADB_USER=${DB_USER:-app}
      - MARIADB_PASSWORD=${DB_PASSWORD:-change-me}
    ports:
      - "127.0.0.1:3306:3306" # MySQL/MariaDB
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: codrandom-web
    environment:
      # Match mariadb service credentials and database
      - DATABASE_URL=mysql://$${DB_USER:-app}:$${DB_PASSWORD:-change-me}@mariadb:3306/$${DB_NAME:-codrandom}
      # Optional: Next.js port can be changed; defaults to 3000
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mariadb-data:
