version: '3.8'
services:
  cockroachdb:
    image: cockroachdb/cockroach:v23.2.9
    command: ["start-single-node", "--insecure"]
    ports:
      - "26257:26257" # SQL
      - "8080:8080"   # Admin UI
    volumes:
      - cockroach-data:/cockroach/cockroach-data

volumes:
  cockroach-data:
