version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-change-root}
      - MARIADB_DATABASE=${DB_NAME:-codrandom}
      - MARIADB_USER=${DB_USER:-app}
      - MARIADB_PASSWORD=${DB_PASSWORD:-change-me}
    ports:
      - "127.0.0.1:3306:3306" # MySQL/MariaDB
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized", "--innodb_buffer_pool_loaded"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 30s
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: codrandom-web
    environment:
      DATABASE_URL: "mysql://${DB_USER:-app}:${DB_PASSWORD:-change-me}@mariadb:3306/${DB_NAME:-codrandom}"
      DB_HOST: mariadb
      DB_PORT: "3306"
      PORT: "3000"
    ports:
      - "3000:3000"
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mariadb-data:
